### ISSUE TITLE
How to use different GraphQLObjectType mutations in one root parameter of the schema?

### ISSUE THREAD

**Issue by nikitamarcius** [facebook/graphql#289] opened 2017-03-23 12:51 UTC
Hi! I want to create different GraphQLObjectType mutation\queries for each separate model.

In present time in GraphQL server we have one schema with two parameters: queries and mutations. 
Each of which accepts GraphQLObjectType and includes differents fields. In library we have some think like this on the example of mutations:

**Mutations:**
UserAdd
UserRemove
ArcicleAdd
MapAddPin
..etc

Root mutations include list of all fields, - yes because we import all fields in one GraphQLObjectType. I want to use for each separate model GraphQLObjectType, that i can get in my library next option:

**Mutations:**
- User
UserAdd
UserRemove
- Arcticle
ArcicleAdd
- Map
MapAddPin

Thanks.

**Comment by robzhu** [comment] 2017-04-28 18:35
If I understand correctly, you would like some capability to organize your mutations hierarchically?

**Comment by nikitamarcius** [comment] 2017-04-28 19:57
@robzhu exactly

**Comment by stubailo** [comment] 2017-05-01 21:59
This is a duplicate of #252

**Comment by wincent** [comment] 2017-05-04 00:14
@stubailo: Is it? I thought #252 was about making implanting mutation/serial-execution semantics at arbitrary points within query operations, whereas this one seems to be about organization within mutation operations.

**Comment by stubailo** [comment] 2017-05-09 07:05
> I want to use for each separate model GraphQLObjectType

My understanding is that @nikitamarcius wants to have separate mutation GraphQL Object Types for each kind of data. To me that sounds the same as being able to mark arbitrary GraphQL Object Types as a "mutation type", which is what #252 is about.

(Note that AFAIK the mutation type can already appear anywhere, if you just return it from a field: `type Query { mutation: Mutation }`)

**Closed** 2017-07-27 15:46 UTC
